### ISSUE TITLE
Add a strftime or equivalent string function

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-expression#1]
I would be highly advantageous for the expression evaluator to take a timestamp and generate an output based on strftime type formats.
For example

```
strftime("2017-09-01T08:57:11.903Z", "%F")
> 2017-09-01

strftime("2017-09-01T08:57:11.903Z", "%Y")
> 2017
```

The significant benefit comes when wanting visualisation output with year, month or date series.

**Comment by stroomdev66** [comment]
How about a `formatDate` function more similar to the one we provide for XSLT?

`formatDate($var, 'patternOut')
`formatDate('2017-09-01T08:57:11.903Z' , 'yyyy') -> 2017`

Furthermore should we also support an input pattern like we do for XSLT?

`formatDate($var, 'patternIn', 'patternOut')
`formatDate('2017/09/13' , 'yyyy/MM/dd', 'yyyy') -> 2017`

Alternatively or in addition to this we could provide a corresponding `parseDate` function that could be nested, e.g.

`formatDate(parseDate($var, 'patternIn'), 'patternOut')
`formatDate(parseDate('2017/09/13' , 'yyyy/MM/dd'), 'yyyy') -> 2017`

**Comment by burnalting** [comment]
Keeping the xslt functions and dashboard functions in parallel is a good idea.

Either option (formatDate or formatDate + parseDate) works.
